source_lang: en

languages:
  - ru
  - de
  - es
  - fr
  - it
  - pt-BR
  - ja
  - ko
  - zh-CN
  - uk
  - tr
  - ar
  - pl

targets:
  - name: "lokit CLI"
    type: gettext
    root: "."
    po_dir: "po"
    pot_file: "po/lokit.pot"
    sources:
      - "."
    keywords:
      - "T"
      - "N:1,2"
